---

info:
  build:
    version: 0.0.1-SNAPSHOT

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    initialization-mode: ALWAYS
    continue-on-error: false
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 600000
      max-lifetime: 900000
      connection-timeout: 600000
  flyway:
    enabled: true
    baseline-version: 1
    baseline-on-migrate: true
    locations:classpath: db/migration
    table: flyway_schema_history
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: ${ENABLE_NEW_SESSION_ON_LAZY:false}
        jdbc:
          lob:
            non_contextual_creation: true
        show-sql: true
        format_sql: true
  jackson:
    default-property-inclusion: NON_NULL

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    web:
      server:
        request:
          autotime:
            percentiles: [0.5, 0.95, 0.99]
      client:
        request:
          autotime:
            percentiles: [0.5, 0.95, 0.99]
          metric-name: 'order_downstream_service'
